@extends('layouts.app')
@php($payable = $kind === 'payable')
@section('title', $payable ? 'Detalhe da conta a pagar' : 'Detalhe da conta a receber')
@section('section', $payable ? 'Contas a pagar' : 'Contas a receber')
@section('page-title', 'Detalhe do título')

@section('content')
<a class="back-link" href="{{ $payable ? route('payables.index') : route('receivables.index') }}">← Voltar para a listagem</a>
<header class="record-hero"><div><span class="eyebrow">{{ $payable ? 'Conta a pagar' : 'Conta a receber' }} · #{{ $record->id }}</span><h2>{{ $lookups['parties'][$payable?$record->fornecedor:$record->cliente] ?? ($payable?$record->fornecedor:($record->cliente?:$record->fornecedor)) }}</h2><p>Documento {{ $record->numero_doc }} · Origem {{ $record->tipo_lancamento ?: 'Gestão' }}</p>@can('payments')<div class="inline-actions"><a class="button ghost" href="{{ route($payable?'payables.edit':'receivables.edit',$record) }}">Editar</a><form method="post" action="{{ route($payable?'payables.destroy':'receivables.destroy',$record) }}" onsubmit="return confirm('Excluir este título?')">@csrf @method('delete')<button class="button danger" type="submit">Excluir</button></form></div>@endcan</div><div class="record-value"><span class="badge warning">{{ $lookups['statuses'][$record->situacao] ?? ($record->situacao ?: 'Pendente') }}</span><strong>R$ {{ number_format((float)$record->valor_total, 2, ',', '.') }}</strong><small>Vencimento {{ $record->dateLabel('data_vencimento') }}</small></div></header>
<div class="detail-grid">
    <section class="panel span-2"><header class="panel-header"><div><h3>Resumo financeiro</h3><p>Dados principais do título</p></div></header><dl class="detail-list"><div><dt>Valor original</dt><dd>R$ {{ number_format((float)$record->valor, 2, ',', '.') }}</dd></div><div><dt>Acréscimo</dt><dd>R$ {{ number_format((float)$record->acrescimo, 2, ',', '.') }}</dd></div><div><dt>Desconto</dt><dd>R$ {{ number_format((float)$record->desconto, 2, ',', '.') }}</dd></div><div><dt>Valor total</dt><dd><strong>R$ {{ number_format((float)$record->valor_total, 2, ',', '.') }}</strong></dd></div><div><dt>Emissão</dt><dd>{{ $record->dateLabel('data_emissao') }}</dd></div><div><dt>Vencimento</dt><dd>{{ $record->dateLabel('data_vencimento') }}</dd></div></dl></section>
    <section class="panel"><header class="panel-header"><div><h3>Classificação</h3><p>Organização contábil</p></div></header><dl class="stacked-details"><div><dt>Conta</dt><dd>{{ $lookups['accounts'][$record->conta] ?? $record->conta }}</dd></div><div><dt>Categoria</dt><dd>{{ $lookups['categories'][$record->categoria] ?? $record->categoria }}</dd></div><div><dt>Centro de custo</dt><dd>{{ $lookups['costCenters'][$record->centrocusto] ?? $record->centrocusto }}</dd></div><div><dt>Competência</dt><dd>{{ $record->competencia }}</dd></div></dl></section>
    <section class="panel span-3"><header class="panel-header"><div><h3>Histórico e observações</h3><p>Rastreabilidade do registro</p></div></header><div class="history"><div><span></span><div><strong>Título cadastrado no Gestão</strong><small>{{ $record->created_at?->format('d/m/Y H:i') }} · Origem {{ $record->tipo_lancamento ?: 'manual' }}</small></div></div><div><span></span><div><strong>Última atualização</strong><small>{{ $record->updated_at?->format('d/m/Y H:i') }}</small></div></div></div>@if($record->obs)<div class="note"><strong>Observações</strong><p>{{ $record->obs }}</p></div>@endif</section>
</div>
@can('payments')<div class="detail-grid section-gap"><section class="panel"><header class="panel-header"><div><h3>Gerar parcelas</h3><p>Divide o valor sem alterar o total.</p></div></header><form class="compact-form" method="post" action="{{ route($payable?'payables.installments':'receivables.installments',$record) }}">@csrf<label class="field"><span>Quantidade</span><input type="number" name="quantity" min="2" max="120" required></label><label class="field"><span>Primeiro vencimento</span><input type="date" name="first_due" required value="{{ $record->getRawOriginal('data_vencimento') }}"></label><button class="button primary">Gerar</button></form></section><section class="panel span-2"><header class="panel-header"><div><h3>Documentos</h3><p>Arquivos privados vinculados ao título.</p></div></header><form class="compact-form" method="post" enctype="multipart/form-data" action="{{ route('documents.store',[$payable?'payable':'receivable',$record->id]) }}">@csrf<input type="file" name="document" required><button class="button primary">Enviar</button></form><div class="document-list">@forelse($documents as $doc)<div><a href="{{ route('documents.download',$doc) }}">{{ $doc->nome_original }}</a><form method="post" action="{{ route('documents.destroy',$doc) }}">@csrf @method('delete')<button class="link-danger">Remover</button></form></div>@empty<small>Nenhum documento anexado.</small>@endforelse</div></section></div>@endcan
@endsection
