@extends('layouts.app')
@section('title','Candidato #'.$record->id)
@section('section','Conciliação v2')
@section('page-title','Candidato #'.$record->id)
@section('content')
<a class="back-link" href="{{ route('reconciliation-v2.show',$session) }}">← Sessão #{{ $session->id }}</a>
<header class="record-hero"><div><span class="eyebrow">Sugestão explicável · {{ $record->engine_version }}</span><h2>{{ $record->type->value }}</h2><p>Assinatura {{ $record->signature_hash }}</p></div><div class="record-value"><strong>{{ $record->score }}/100</strong><span class="badge info">{{ $record->confidence }}</span><span class="badge {{ $record->status->value==='PENDING'?'warning':'neutral' }}">{{ $record->status->value }}</span></div></header>
<div class="detail-grid"><section class="panel span-2"><header class="panel-header"><div><h3>Composição proposta</h3><p>Valores disponíveis capturados na geração; serão revalidados no aceite.</p></div></header><div class="table-wrap"><table><thead><tr><th>Origem</th><th>ID</th><th>Contexto</th><th>Proposto</th></tr></thead><tbody>@foreach($record->titleAllocations as $item)<tr><td>Título/parcela</td><td>#{{ $item->financial_title_id }} / {{ $item->title_installment_id }}</td><td>{{ $item->financialTitle->party_name }} · {{ $item->financialTitle->document_number }}</td><td>R$ {{ number_format((float)$item->proposed_amount,2,',','.') }}</td></tr>@endforeach @foreach($record->transactionAllocations as $item)<tr><td>Banco</td><td>#{{ $item->bank_transaction_id }}</td><td>{{ $item->bankTransaction->transaction_date->format('d/m/Y') }} · {{ $item->bankTransaction->description_original }}</td><td>R$ {{ number_format((float)$item->proposed_amount,2,',','.') }}</td></tr>@endforeach</tbody></table></div></section><section class="panel"><header class="panel-header"><div><h3>Evidências</h3><p>Impactos determinísticos, sem conteúdo sensível completo.</p></div></header><div class="history">@foreach(($record->evidence['signals'] ?? []) as $signal)<div><span></span><div><strong>{{ $signal['code'] }}</strong><small>Impacto +{{ $signal['impact'] }}</small></div></div>@endforeach</div><div class="note"><p>{{ $record->evidence['explanation'] ?? '' }}</p></div></section></div>
@if($record->status->value==='PENDING') @can('reconciliation:manage')<section class="panel section-gap"><header class="panel-header"><div><h3>Decisão humana obrigatória</h3><p>Aceitar chama o mesmo serviço manual e não liquida títulos.</p></div></header><div class="compact-form"><form method="post" action="{{ route('reconciliation-v2.candidates.accept',[$session,$record]) }}">@csrf<button class="button primary">Aceitar e revalidar</button></form><form method="post" action="{{ route('reconciliation-v2.candidates.reject',[$session,$record]) }}" class="compact-form">@csrf<label class="field"><span>Motivo obrigatório</span><input name="reason" required maxlength="1000"></label><button class="button danger">Rejeitar</button></form></div></section>@endcan @endif
@if($record->decision_reason)<div class="alert warning section-gap">Decisão: {{ $record->decision_reason }}</div>@endif
@endsection
